#!/usr/bin/env python3
import os
import subprocess


def updates():
    output = ""
    try:
        output = subprocess.check_output(["checkupdates"]).decode("utf-8")
    except:
        return 0

    lines = [line for line in output.split('\n') if line]

    return len(lines)


def aur():
    output = ""
    try:
        output = subprocess.check_output(["yay", "-Qua"]).decode('utf-8')
    except:
        return 0

    lines = [line for line in output.split('\n') if line]

    return len(lines)


message = "<span color='{0}'>{1}</span>"
color = "yellow"

pacman_updates = "{0} pacman".format(updates())
aur_updates = "{0} pacman".format(updates())

print(message.format(color, pacman_updates))
print(message.format(color, aur_updates))
