#!/bin/bash
TMPBG=/tmp/screen.png

#1920x1080
RES=$(xdpyinfo | awk '/dimensions:/ { print $2 }')

ffmpeg -f x11grab -video_size $RES -y -i $DISPLAY -filter_complex "boxblur=16:1" -vframes 1 $TMPBG
i3lock -i $TMPBG
